#import "../lib.typ": *
#import "../fermat.typ": *

#let meta = (
  title: "Conclusiones y próximos pasos",
  date: "2026-12-28",
  series: "fermat",
  part: 14,
  summary: [Qué aprendimos sobre cuándo ayuda (y cuándo no) la distancia de Fermat en clasificación, y las líneas de trabajo que quedan abiertas.],
  status: "published",
  lang: "es",
)
#show: post.with(..meta)

#callout(title: "En este post")[
  *¿Cuándo conviene la distancia de Fermat?* Cuando la variedad es muy curva o está ralamente muestreada, los atributos comparten escala y hay pocas dimensiones de ruido puro; en vecindarios pequeños no se distingue de la euclídea. Este post reúne las conclusiones de la tesis, las líneas de trabajo futuro y una nota sobre el uso de inteligencia artificial en su redacción.
]


Implementamos la distancia de Fermat muestral como una métrica compatible con los clasificadores de `scikit-learn` --- con estimación _out-of-sample_ y rutinas propias basadas en primitivos de `numpy` y `scipy` --- y sobre ella dos clasificadores, #fkdc y #fkn, que comparamos en #reps corridas de entrenamiento y evaluación con sus pares euclídeos y cuatro alternativas de referencia en 20 datasets. Por $R^2$ mediano, #fkdc obtuvo el máximo en 7 datasets y #fkn en 5 --- dos de ellos empatados con #kn ---; #kdc, la implementación del clasificador de @loubesKernelbasedClassifierRiemannian2008, en otros 2. Por exactitud la ventaja se diluye, y #svc resulta casi imbatible.

Los experimentos son consistentes entre sí sobre _cuándo_ aporta la distancia de Fermat. En los vecindarios pequeños --- $k = 1$ en #fkn, $h$ chico en #fkdc --- coincide con la euclídea, y en datasets bien muestreados la superficie de pérdida de #fkdc exhibe un "risco" de parametrizaciones equivalentes, $log h prop alpha$, a lo largo del cual el efecto de $alpha$ se puede sustituir por otro $h$: allí la regla de parsimonia elige $alpha = 1$ y #fkdc colapsa a #kdc con un ancho de banda apenas distinto. Cuando #fkdc o #fkn aventajan a sus pares, la ventaja proviene de dos efectos: una interacción entre la regla de parsimonia y el espacio de hiperparámetros ampliado, que en `lunas_lo` y `espirales_lo` explica toda la diferencia; y, en `helices_0` y `hueveras_0`, parametrizaciones con el mismo $k$ o $h$ que la variante euclídea pero $alpha > 1$, es decir, una mejora neta atribuible a #sfd. Esta es consistente con la observación de #cite(<bijralSemisupervisedLearningDensity2011>, form:"prose") de que basta con aprender $alpha$ sin estimar la dimensión intrínseca. El aporte más claro es cualitativo: la distancia de Fermat permite agrandar el vecindario sin cruzar a la otra variedad, con lo que #fkn se vuelve robusto a la elección de $k$ y las fronteras de #fkdc se alinean con la forma de las variedades, propiedad que no se reduce fácilmente a una métrica escalar.

Sobre _cuándo no_, aprendimos dos cosas. La primera es que las dimensiones de ruido son letales para los métodos locales: con 12 dimensiones de ruido añadidas a los datasets 3D, la familia $cal(K)$ se desploma, la distancia de Fermat no lo remedia --- hereda las aristas euclídeas que el ruido alarga --- mientras que #gbt, que interroga una variable a la vez, apenas se inmuta. La segunda no la anticipamos debidamente: la familia $cal(K)$ no es invariante a la escala de los atributos. En `pinguinos`, un atributo en gramos frente a tres en milímetros bastó para que #fkdc confundiera dos especies por completo, y estandarizar dentro del entrenamiento lo devolvió al nivel del mejor método en la Tarea, regresión logística; en `digitos`, de escala ya homogénea, la misma estandarización lo perjudicó. Nuestra decisión de preprocesar al mínimo fue deliberada, pero convierte las comparaciones sobre datasets "orgánicos" en comparaciones entre algoritmos con y sin tratamiento de escala, y así deben leerse.

La distancia de Fermat aumenta la varianza entre repeticiones respecto de la euclídea, con _outliers_ negativos ocasionales (`eslabones_0`, `helices_0`): es el costo del espacio de hiperparámetros ampliado. Y el costo computacional, aunque varios órdenes de magnitud mayor que el de la distancia euclídea, no fue un obstáculo: las 4000 tareas del cuerpo principal corrieron en unas 12 horas en una computadora personal #footnote[MacBook Air M1 2020, 8 GB de RAM, 256 GB SSD.].

Ningún algoritmo evaluado fue universalmente óptimo, y todos tuvieron al menos un dataset favorable. La distancia de Fermat y nuestras implementaciones de #fkdc y #fkn son una herramienta más en la paleta del investigador, con un dominio de aplicación que empezamos a delimitar: variedades muy curvas o ralamente muestreadas, atributos en una escala común y pocas dimensiones de ruido puro.

= Trabajo futuro <trabajo-futuro>

Tres líneas de trabajo se desprenden directamente de lo anterior. Las dos primeras apuntan a lo mismo: pasar de constatar _cuándo_ la distancia de Fermat ayuda a poder anticiparlo. La tercera es saldar una deuda teórica.

La primera es la escala de los atributos. Los experimentos de #parte("fermat-13-datasets-organicos")[sensibilidad a la escala de los atributos] muestran que estandarizar es indispensable cuando las unidades son arbitrarias (`pinguinos`, `vino`) y contraproducente cuando la escala ya ordena las direcciones (`digitos`, las componentes principales de `mnist`), pero no dicen dónde está la frontera entre ambos casos. Vale la pena estudiarla sistemáticamente: sobre las variedades sintéticas, estirando una coordenada a la vez y midiendo cuánto tarda en degradarse cada clasificador; sobre los datasets reales, comparando estandarización, reescalado robusto y ninguno. Conceptualmente, estandarizar no es más que una métrica diagonal aprendida de la manera más burda posible --- una $HH in cal(D)$ fija de antemano, en los términos de la #parte("fermat-03-maldicion-y-variedades")[KDE multivariada] ---, así que la generalización natural es aprender esa diagonal junto con $alpha$, en lugar de decidirla a mano. Ese es también el camino para incorporar la reducción lineal de dimensionalidad que salvó a `mnist` como un paso más del mismo pipeline. De hecho, así empezó este trabajo: en el _commit_ #link("https://github.com/capitantoto/fermat/blob/9d12fad3b0a110e12eec99b47f10c47b75043b18/fkdc/algoritmos.py#L19-L27")[`9d12fad`] del repositorio, la grilla de cada clasificador incluía un escalador opcional y una PCA que conservara el 80, 90 o 95 % de la varianza como pasos previos del _pipeline_, pero antes de la corrida principal se los quitó para no agregar otro eje al análisis. Retomar el estudio desde allí sería una forma sistemática de responder cuándo conviene cada pretratamiento.

La segunda es la simbiosis entre $h$ y $alpha$. En los datasets bien muestreados, la superficie de pérdida de #fkdc exhibe una región $log h prop alpha$ a lo largo de la cual ambos hiperparámetros son intercambiables, y la ventaja de #fkdc sobre #kdc se reduce a cómo la regla de parsimonia recorre ese espacio; solo cuando la curvatura de la variedad es comparable a la distancia entre observaciones --- `helices_0`, `hueveras_0` --- aparece un $alpha > 1$ que ningún $h$ sustituye. Conjeturo que la magnitud relevante es el cociente entre la escala localmente lineal de la variedad, en el sentido de #cite(<brandChartingManifold2002>, form: "prose"), y la separación típica entre observaciones vecinas: cuando es grande, todo vecindario útil cae dentro del radio de inyectividad y $cal(D)_(f, beta) prop norm(dot)$; cuando es pequeño, hay que tomar $h > "iny" MM$, fuera del supuesto de #cite(<pelletierKernelDensityEstimation2005>, form: "prose"), y la distancia de Fermat es la que permite seguir agrandando el vecindario sin cruzar a otra variedad. Estimar ese cociente a partir de la muestra --- la tasa $c(r)$ de Brand es un candidato --- daría un criterio _a priori_ para saber si vale la pena pagar el costo de #sfd, y un diseño experimental natural: variedades de curvatura controlada muestreadas con $N$ decreciente hasta cruzar la frontera. Como detalle menor, la grilla $alpha in [1, 4]$ podría ampliarse; #cite(<bijralSemisupervisedLearningDensity2011>, form: "prose") reportan buenos resultados con $alpha = 8$.

La tercera es la densidad de volumen y, con ella, la consistencia de #fkdc. Tomamos $theta equiv 1$ (#parte("fermat-08-propuesta")[omisión de la densidad de volumen]) con un argumento cualitativo; falta ponerlo a prueba. La esfera $S^2$ ofrece el experimento más barato, porque allí $theta_p (q)$ tiene la forma cerrada de #cite(<henryKernelDensityEstimation2009>, form: "prose") reproducida en la #parte("fermat-05-densidades-en-variedades")[definición de función de densidad de volumen]: basta muestrear clases sobre la esfera y entrenar #kdc con y sin el factor para medir cuánto cambia el $R^2$ en función de $h$, y a partir de qué curvatura relativa a $h$ el supuesto deja de ser razonable. El paso siguiente sería estimar $theta$ en lugar de ignorarla, retomando el hilo de la #parte("fermat-08-propuesta")[omisión de la densidad de volumen]: la formulación de #cite(<besseManifoldsAllWhose1978>, form: "prose", supplement:[§6.3]) en términos de campos de Jacobi describe cómo se abren las geodésicas alrededor de $p$. Una medida muestral de lo mismo la ofrece el análisis de componentes principales local de #cite(<vincentManifoldParzenWindows2002>, form: "prose"): estimado el espacio tangente en cada observación, cuánto cambia --- cuánto rota --- ese subespacio entre una observación y sus vecinas es, precisamente, una medida de cómo se curva la variedad alrededor de ellas. Si esa correspondencia se pudiera hacer precisa, daría una corrección de $theta$ computable a partir de los vecindarios según distancia de Fermat que ya construimos.

Del lado de la teoría, el estimador que de hecho entrenamos no está cubierto por ningún teorema: #cite(<pelletierKernelDensityEstimation2005>, form: "prose") supone conocida la distancia $dg$, y #cite(<groismanNonhomogeneousEuclideanFirstpassage2022>, form: "prose") garantiza la convergencia de #sfd a $cal(D)_(f, beta)$, pero no hay un resultado que combine ambos y diga que el núcleo evaluado sobre #sfd estima consistentemente _alguna_ densidad. Sospecho que la respuesta pasa por observar que la distancia de Fermat es la distancia de una métrica que depende de la propia densidad, y que respecto de esa métrica cambian tanto la densidad que se estima como su densidad de volumen; si así fuera, $alpha$ y $theta$ no serían independientes, lo que daría un sentido preciso a la observación empírica de que un $alpha > 1$ solo aparece donde la curvatura importa. Un tratamiento formal de esta relación excede las capacidades del autor.

Quedan, por último, tres ajustes de diseño experimental que no cambian las preguntas pero sí la calidad de las respuestas: 
- reemplazar el grafo completo por el de $k$ vecinos con el $k = O(2^(d_MM) ln N)$ que garantiza #cite(<chuExactComputationManifold2019>, form: "prose"), para escalar #sfd a muestras con $10$ veces o más observaciones sin que "explote" el tiempo de cómputo #footnote[Nobleza obliga, el paquete `fermat` de #cite(<sapienzaWeightedGeodesicDistance2018>, form: "prose"), que no usamos por carecer de estimación _out-of-sample_, ya implementa aproximaciones de este tipo: geodésicas sobre el grafo de $k$ vecinos y distancias vía un subconjunto de "puntos de referencia" (_landmarks_) en lugar del grafo completo.];
- entrenar los clasificadores blandos directamente con el $R^2$ de McFadden como _score_ y calibrar #svc para poder compararlo por $R^2$, y
- reemplazar el recuento de podios de los #parte("fermat-10-resultados-en-el-plano")[resultados] por una comparación estadística más seria sobre los 20 datasets, que dé cuenta de los "empates" y de la variabilidad entre semillas.

= Nota sobre el uso de inteligencia artificial

Durante la redacción del grueso de la tesis, entre 2023 y 2025, no se utilizó ningún asistente basado en LLM. Así, la selección y presentación del marco teórico, el diseño experimental, la implementación, los resultados y su interpretación son míos. Durante el proceso de revisión de los resultados y edición en 2026, utilicé un asistente de inteligencia artificial (_Claude_ en sus versiones _Opus 4.6, 5_ y _Fable 5.1_, de Anthropic). A la luz de las crecientes capacidades de estos sistemas, corresponde declarar con precisión qué hizo y qué no.

Entre febrero y junio de 2026, la asistencia fue estrictamente de forma: corrección ortográfica y gramatical, sugerencias de estilo, formato en Typst, generación de figuras a partir de los datos y resolución de tareas mecánicas. En la revisión final, en septiembre de 2026, el alcance de la asistencia fue mayor: el asistente revisó la corrección de varias definiciones, y redactó primeras versiones de pasajes expositivos (Brand 2002, la omisión de la densidad de volumen), propuso los experimentos de #parte("fermat-13-datasets-organicos")[sensibilidad a la escala de los atributos] reemplazando afirmaciones previas más imprecisas sobre el (mal) rendimiento de #fkdc en `pinguinos` y `vino`, propuso recortes a lo que se afirmaba en las conclusiones y asistió en la correcta atribución de las líneas de trabajo futuro.

En todos los casos yo, Gonzalo Barrera Borla, examiné, verifiqué y decidí qué adoptar --- muchas veces iterando "a mano" y "con IA" alternadamente sobre el mismo fragmento --- hasta estar personalmente satisfecho con lo expuesto, siendo todavía capaz de defender el contenido a ciegas ante un jurado. El texto final es mi entera responsabilidad. La historia completa está en los _commits_ del repositorio, marcados con la leyenda "Asistido por IA" cuando así corresponde.

= Lo que viene en el blog

- Un repaso de los papers más citados en la tesis.
- Sumar al _benchmark_ clasificadores _zero-shot_ basados en LLMs y _embeddings_.



#bibliography("/refs.bib", title: "Referencias")
